### PR TITLE
Fix wrong link path

### PR DESCRIPTION
**Pull request by djKooks**
Some of link to index linked in brand `Oryx 2` in main page has wrong path.
Please look on. Thanks.

### CODE REVIEW

**Comment by srowen** [comment]
This part of the doc is auto-generated, actually. It really has to be fixed in `src/site/site.xml`. I think the link should just be "/"?

**Comment by djKooks** [comment]
@srowen Oh, I didn't knew of auto generator.
Because all of sub documents, such as admin, developer, etc. are all in /docs directory, it needs to add `../` to find `index.html`.
How about make a document for `overview` page and put it on docs directory?

**Comment by srowen** [comment]
No, you just need to change the one link in site.xml. I can do it if it's inconvenient.

**Comment by djKooks** [comment]
@srowen No problem to do it on my side, but could you tell me how to generate document via source code? Is it generating with `mvn` command?

**Comment by srowen** [comment]
The docs are generated with the release using mvn site. However on second thought it is probably easiest to both change site.xml and hotfix all of the generated HTML as you did, manually

**Comment by djKooks** [comment]
@srowen Sorry, it keep causes error in `mvn site` command(though `mvn package` works well). I tried to update site.xml as you commented, but not sure about it. Please let me know if there is something wrong.

**Comment by srowen** [comment]
Yeah that's why I say don't try to build the docs. Your change to the HTML isn't consistent with site.xml though. I can just make the change ...

**Comment by djKooks** [comment]
@srowen Okay. Would you go on this problem?

**Comment by srowen** [comment]
Should be fixed in https://github.com/OryxProject/oryx/commit/212d62c91210ce9d10ec15f68edb88ae70f9d1d9

**Comment by djKooks** [comment]
@srowen Thanks!

**Pull request closed without merging**
