### PR TITLE
Swap Koloboke for Eclipse Collections

### PR DESCRIPTION
**Pull request by srowen**
See #304 . Unfortunately it does seem to increase memory usage about 10% and slow down /recommend about 10%.

CC @stiv-yakovenko

### CODE REVIEW

**Comment by stiv-yakovenko** [comment]
Tried to checkout entire branch by commit id, but I have same problem building it with maven as if i checkout main branch. Now I can only build code from .zip file from releases tab.

**Comment by srowen** [comment]
@stiv-yakovenko it would help if you told me what the error was. The build works fine for me and always has. `mvn -DskipTests clean install` from the top level should always get you all artifacts.

Here are the JARs built from this branch: https://drive.google.com/open?id=1MhBFnS_T0Ji5uW4Sjl4E3QqoLh66dPlc

**Comment by stiv-yakovenko** [comment]
I've just retried, and it has built successfully. pom.xml has references to clouderra repository, may be previously these dependencies were not in place...

**Comment by srowen** [comment]
The Cloudera repo doesn't matter unless you are enabling the Cloudera profile. I could move the repository definition into the profile for clarity, but should not matter.

**Comment by srowen** [comment]
@stiv-yakovenko have you had a chance to try these out? tests pass, which is good, and a load test I ran succeeded.

**Comment by stiv-yakovenko** [comment]
Worked correctly for me, you can push this to release I think

**Comment by stiv-yakovenko** [comment]
>merged commit c7a8854 into OryxProject:master
cool!!

**Pull request merged**
