### PR TITLE
Define fetch.message.max.bytes for OryxUpdate topic in Speed and Service layers

### PR DESCRIPTION
**Pull request by dsdinter**
Define fetch.message.max.bytes for OryxUpdate topic in Speed and Service layers #224

### CODE REVIEW

**Comment by srowen** [comment]
Looks good to me. I might even increase this further and change one more instance of `Consumer` that is only used in tests. I can follow up with that.

**Comment by srowen** [comment]
There may be more to this:
http://www.cloudera.com/content/cloudera/en/documentation/cloudera-kafka/latest/topics/kafka_performance.html

Increasing the broker's max has nontrivial memory implications, but it's also needed to process large messages.

I could add this info to the docs, but I think I also need to support compressed messages. I wonder if that brings the max message size down a lot? like, do you think 10MB or so would work for your use case then?

**Comment by dsdinter** [comment]
So far the size of the model and feature matrices is below 5MB so it should be fine with 10MB for quite some time even without compression. In any case, it sounds good idea to add compression in OryxUpdate Topic as this topic is mainly used for bulky messages. As the model and features are kept in gzip format in HDFS sounds good to stick to gzip right? Not sure there will still be some serialisation needed from the producer though.

Thanks.

**Comment by srowen** [comment]
Yeah, I've just tried turning on Snappy compression for the topics and it seems OK. The compression is entirely internal to Kafka so the choice doesn't matter much. Yes I went with gzip for the HDFS files since someone might want to read them, and it's longer term storage, so compatibility and size matter more, so gzip is better than snappy.

OK, I will make some updates that enable compression but actually backs off the max message size a bit. Note you'll also need to set  `message.max.bytes` and `replica.fetch.max.bytes` in your broker to make any of this matter, I think, or else the broker won't consume a message of this size anyway. That's outside the app. I'm adding a note about this in the docs.

**Comment by srowen** [comment]
After some reading and testing, I find that compression does work, but it's the uncompressed size that matters with regards to these properties. So I think I might even increase your `fetch.message.max.bytes`.

It's possible to set `max.message.bytes` per-topic (yes, not the same name as the broker's `message.max.bytes` property for the same thing), which is good, since actually it would be bad if this required the entire Kafka broker to have a bigger max message size. However there is no per-topic equivalent of `replica.fetch.max.bytes`. This means big messages would not be replicated, unless the broker config were changed. Something to just document, I guess.

Finally, I'm trying to figure out if there's any draw-back to just setting a large `fetch.message.max.bytes` and `max.message.bytes`. Since each topic has only 1 partition, by design, the impact should be pretty limited if the configuration is per topic. Each consumer has to allocate a big chunk of memory now as its buffer, but even 64MB isn't so bad as there is just one per layer process.

**Comment by dsdinter** [comment]
Good to hear compression works, would you consider compressing the input topic as well? I would imagine there may be other use cases to leverage this but not sure on the ALS app.

I will have more time next week to analyse & evaluate these changes as well.


Thanks.

**Comment by srowen** [comment]
Yeah, the apps will set compression on their messages to the input topic. External producers can do the same. It's all transparent since it happens inside kafka.

**Pull request merged**
