### PR TITLE
Switch to direct Kafka receiver. Manually manage ZK offsets. Some related refactoring.

### PR DESCRIPTION
**Pull request by srowen**
Addresses issue #192

### CODE REVIEW

**Comment by smarthi** [comment]
Looks good to merge

**Comment by srowen** [comment]
Yeah, this change was more bloated than I expected since the new receiver requires you to manage offsets in ZK manually (or else, it manages offsets in Spark, and requires checkpointing, which struck me as quite redundant?) And some was related cleanup. 

But in the end it's not too bad and I like this model better because it's simpler. Before, it would read from Kafka in small sips and persist the data again in Spark in memory and on disk. Now, it just waits and pulls a range of messages from Kafka at the end of each interval directly. More simple = less scary.

**Comment by dsdinter** [comment]
Hi,
I am actually testing the build based on latest master branch (Which I assume includes this new feature), and it appears I am hitting some issues around Spark Streaming/Kafka libraries used for compilation differing from the actual libraries used at runtime:

2015-05-22 15:15:51,878 INFO  AbstractSparkLayer:149 Starting SparkContext for master yarn-client, interval 10 seconds
2015-05-22 15:15:52,799 INFO  Remoting:74 Starting remoting
2015-05-22 15:15:52,961 INFO  Remoting:74 Remoting started; listening on addresses :[akka.tcp://sparkDriver@server.com:58510]
2015-05-22 15:15:52,963 INFO  Remoting:74 Remoting now listens on addresses: [akka.tcp://sparkDriver@server.com:58510]
2015-05-22 15:15:53,191 INFO  Server:272 jetty-8.y.z-SNAPSHOT
2015-05-22 15:15:53,203 INFO  AbstractConnector:338 Started SocketConnector@0.0.0.0:51536
2015-05-22 15:15:53,283 INFO  Server:272 jetty-8.y.z-SNAPSHOT
2015-05-22 15:15:53,300 INFO  AbstractConnector:338 Started SelectChannelConnector@0.0.0.0:64041
2015-05-22 15:15:54,078 WARN  NativeCodeLoader:62 Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-05-22 15:16:04,230 INFO  SpeedLayer:99 Creating message stream from topic
2015-05-22 15:16:04,441 INFO  AbstractSparkLayer:216 Initial offsets: {[OryxInput,1]=0, [OryxInput,0]=0}
2015-05-22 15:16:04,763 INFO  SpeedLayer:139 Starting Spark Streaming
2015-05-22 15:16:04,823 INFO  SpeedLayer:146 Spark Streaming is running
2015-05-22 15:16:11,014 WARN  TaskSetManager:71 Lost task 0.0 in stage 0.0 (TID 0, server.com): java.lang.ClassCastException: cannot assign instance of scala.None$ to field org.apache.spark.scheduler.Task.metrics of type scala.Option in instance of org.apache.spark.scheduler.ResultTask
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:68)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:94)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:185)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

I am assuming the libraries impacted are around Spark streaming and Kafka because if I play with the Maven settings around providing or not spark-streaming-kafka_${scala.minor.version} library it actually fails at the same point but with different error (Either classnotfound or issues similar to https://www.mail-archive.com/dev@spark.apache.org/msg09268.html reported by Owen back in Dec if actually spark-examples is not included in the CLASSPATH). I actually tried userClassPathFirst but is not making any effect either.

Have you faced similar issues? I am using CDH 5.4.0 and tried both versions of Kafka available 0.8.2.0-1.kafka1.3.0.p0.29/0.8.2.0-1.kafka1.2.0.p0.2


Regards.

**Comment by srowen** [comment]
Hm... yes I've seen things like this before and they're all due to classloader confusion. I don't recall this particular manifestation. What I do know is that userClassPathFirst seems to cause errors, and so I don't turn it on. Are you using your own app or a built-in app? the built-in ones seem to work, or at least, I spent several days testing them last week and didn't see any problem. I'd certainly mark all of the Spark/Hadoop/Kafka deps as `provided`. Does that give any clue about something that's different between what you're doing and the plain vanilla apps?

**Comment by dsdinter** [comment]
It works now! It seems the Maven server used at the client site was keeping outdated libraries, after refreshing the project and trying from home worked.
I am actually testing ALS with the 20M Movielens dataset as worst case scenario before testing client datasets, so I hope this will help to validate stability of 2.0.0-alpha-2.
I had to reconfigure Kafka increasing max size & YARN memory settings among other things, so I can contribute with some recommended settings.

Thanks.

**Comment by srowen** [comment]
That's great, yes please. I'm putting out the alpha 2 shortly and hope to
get more external feedback to validate it.

Sometimes in the case of snapshot builds, you need "mvn -U ..." to force it
to look for new snapshots.

**Pull request merged**
